SET FOREIGN_KEY_CHECKS=0;
SET AUTOCOMMIT = 0;


DROP TABLE IF EXISTS `Customers`;
DROP TABLE IF EXISTS `Departments`;
DROP TABLE IF EXISTS `Products`;
DROP TABLE IF EXISTS `Employees`;
DROP TABLE IF EXISTS `Invoices`;
DROP TABLE IF EXISTS `InvoicesProducts`;

SET FOREIGN_KEY_CHECKS=1;
COMMIT;